### ISSUE TITLE
Filter compounds by target confidence

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/nf-lv-viz#2]
It'd be nice to agree upon a set of compounds/targets that we firmly believe in both to only show the most confident predictions and also reduce the large number of compounds- maybe thresholding the drug/target information like we did for DTEN here: https://github.com/Sage-Bionetworks/dten/blob/50ae4616873b7c168d819598b5c0af3694c694d9/R/dtex.R#L17

**Comment by allaway** [comment]
In this case, the targets are thresholded to only fairly potent interactions (pchembl > 8) and from there I also pick the top twenty compounds for a given gene (also as measured by pchembl).

This is done on app initiation, so it is pretty easy to tweak this if desired. 

```
drug_targets <- drug_targets %>% 
  filter(mean_pchembl > 8) %>% 
  mutate(gene= hugo_gene) %>% 
  group_by(gene) %>% 
  top_n(20, mean_pchembl) %>% 
  select(gene, std_name) 
```
